services:
  attacker-0:
    image: ubuntu:noble
    container_name: attacker-0
    networks:
      - suricata_net
    tty: true
    stdin_open: true
    volumes:
      - ./attacker-0/scripts:/scripts
    command: [
      "/scripts/setup.sh"
    ]
    depends_on:
      - victim

  attacker-ss:
    image: ubuntu:noble
    container_name: attacker-ss
    networks:
      - suricata_net
    tty: true
    stdin_open: true
    volumes:
      - ./attacker-ss/scripts:/scripts
    command: [
      "/scripts/setup.sh"
    ]
    depends_on:
      - victim

  attacker-su:
    image: ubuntu:noble
    container_name: attacker-su
    networks:
      - suricata_net
    tty: true
    stdin_open: true
    volumes:
      - ./attacker-su/scripts:/scripts
    command: [
      "/scripts/setup.sh"
    ]
    depends_on:
      - victim

  attacker-sx:
    image: ubuntu:noble
    container_name: attacker-sx
    networks:
      - suricata_net
    tty: true
    stdin_open: true
    volumes:
      - ./attacker-sx/scripts:/scripts
    command: [
      "/scripts/setup.sh"
    ]
    depends_on:
      - victim

  victim:
    image: alpine:latest
    container_name: victim
    networks:
      - suricata_net
    tty: true
    ports:
      - 80:80
    stdin_open: true
    command: [
      "sh", "-c", "apk add --no-cache python3 && python3 -m http.server 80"
    ]

networks:
  suricata_net:
    driver: bridge
